// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoAPI.DAL;

#nullable disable

namespace ToDoAPI.DAL.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220608094253_seedingData")]
    partial class seedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToDoAPI.Model.Models.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("EntBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EntDt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModDt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ToDos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntDt = new DateTime(2022, 6, 8, 15, 12, 52, 996, DateTimeKind.Local).AddTicks(1249),
                            IsCompleted = false,
                            ModDt = new DateTime(2022, 6, 8, 15, 12, 52, 996, DateTimeKind.Local).AddTicks(1263),
                            Name = "Test1"
                        },
                        new
                        {
                            Id = 2,
                            EntDt = new DateTime(2022, 6, 8, 15, 12, 52, 996, DateTimeKind.Local).AddTicks(1265),
                            IsCompleted = false,
                            ModDt = new DateTime(2022, 6, 8, 15, 12, 52, 996, DateTimeKind.Local).AddTicks(1266),
                            Name = "Test2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
